[package]
name = "locktick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["parking_lot"]
parking_lot = ["dep:parking_lot"]

[dependencies]
backtrace = "0.3"
parking_lot = { version = "0.12", optional = true }
simple_moving_average = "1"
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = "0.3"
